### ISSUE TITLE
Ajax returning Error code 0

### ISSUE THREAD

**Issue by kylehalleman** [umbrellajs/umbrella#71] opened 2016-06-09 15:39 UTC
I'm using the ajax function and although each request is successful and I get the correct body and response, the error parameter keeps coming back with an `Error: 0`. Not sure if I'm making an improper request or else the load event in the Ajax function (looking at source code) is triggering early ([MDN says 0 is the code before the request is complete](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/status))

**Comment by franciscop** [comment] 2016-06-09 15:42
The whole AJAX part should be properly tested and cleaned, for which we need a small test server. So it's entirely possible that it's a bug. Could you share a bit of the code you are using, please?

**Comment by kylehalleman** [comment] 2016-06-09 16:01
It was a basic call to a file, with no options passed. I was developing this locally and calling to the file system (with Chrome's web security disabled). When I threw the files up on a server the error parameter was `null` (as expected) and not an Error object with a code of 0, so I'm guessing it has something to do with working locally off the file system.

**Comment by jereze** [comment] 2016-06-12 17:19
From what I see, the sent request is always with the method `OPTIONS` (not `GET` or `POST`).
http://codepen.io/jereze/pen/zBqrXO

**Comment by franciscop** [comment] 2016-06-18 22:02
That would also be an error, @jereze . I'll fix it ASAP.

**Comment by franciscop** [comment] 2016-07-20 10:24
Digging deep into the `OPTIONS` issue, it seems to be making the request when you do a CORS (Cross Origin Resource Sharing), AKA different domain request:

- http://stackoverflow.com/questions/8163703/cross-domain-ajax-doesnt-send-x-requested-with-header
- http://stackoverflow.com/questions/1099787/jquery-ajax-post-sending-options-as-request-method-in-firefox

This is due to a combination of adding an `X-` header (which is `X-Requested-With` in this case) AND making a Cross-Domain petition. I have confirmed that without these lines:

```
opt.headers['X-Requested-With'] = opt.headers['X-Requested-With'] || 'XMLHttpRequest';
```

The `GET` petition works as expected, and I just created some tests to check it further. I am really busy recently so I cannot really commit so much time to fix this, sorry.

**Comment by franciscop** [comment] 2016-07-20 10:51
The original issue should be fixed, since I was checking (incorrectly) for errors as NOT 2xx and NOT 3xx, while the true is that errors are only 4xx and 5xx. However I'll keep this open for the `OPTIONS` issue

**Comment by jereze** [comment] 2016-07-21 15:49
Thanks for the follow up.

**Comment by franciscop** [comment] 2016-08-09 19:02
The tests are up and running and it returns correctly a `GET`, `POST`, `PUT` and `DELETE` locally.

**Closed by franciscop** 2016-08-09 19:02 UTC

**Comment by jereze** [comment] 2016-08-12 18:06
👍
